### PR TITLE
Feat/image-input

### LINKED ISSUE #241: File picker option
# FEATURE DESCRIPTION

Create new option here:

Screenshot 2024-04-24 at 16 45 49

It will open file picker:

image

It can return object or it can just return full path of this file for another use in javascript.

# EXAMPLE USE CASE

I have modal to create new project and I would like to set the image cover for this. The modal will return me the full path of file I select with this new feature. And in javascript I will copy this file into project folder and change his name.

### PR DESCRIPTION
**Pull request by danielo515**
This adds a new input specific for images.
This will import the image into your vault and give you a reference to the generated TFile

Fixes #241 (at least for images)

### CODE REVIEW

**Comment by dxcore35** [comment]
Can we make that i can import any file not just image? Just let it general file picker, regardless what the file is

**Comment by danielo515** [comment]
I would prefer to have a separate input for that. I want to provide the best user experience, and the images deserve special treatment IMO.
Will add a generic file input as soon as I can

**Comment by dxcore35** [comment]
If this is the case, you should provide more functionality for this, like image optimization, convert it to jpg, change resolutions, etc.. in this case the separated modal make sense.

**Comment by dxcore35** [comment]
https://github.com/danielo515/obsidian-modal-form/issues/341

**Pull request merged**
